export const rulesText = [
  "Your password must be at least five characters",
  "Your password must include a number",
  "Your password must include an uppercase letter",
  "Your password must include a special character",
  "The digits in your password must add up to 25",
  "Your password must include a month of the year",
  "Your password must include a Roman numeral",
  "Your password must include one of our sponsors",
  "The Roman numerals in your password should multiply to 35",
  "Your password must include this CAPTCHA",
  "Your password must include today’s Wordle answer",
  "Your password must include a two-letter symbol from the periodic table",
  "Your password must include the current phase of the moon as an emoji",
  "Your password must include the name of this country",
  "Your password must include a leap year",
  "Your password must include the best move in algebraic chess notation",
  "🥚 This is my chicken Paul. He hasn’t hatched yet. Please put him in your password and keep him safe",
  "The elements in your password must have atomic numbers that add up to 200",
  "All the vowels in your password must be bolded",
  "Oh no! Your password is on fire 🔥. Quick, put it out!",
  "Your password is not strong enough 🏋️‍♂️",
  "Your password must contain one of the following affirmations: I am loved | I am worthy | I am enough",
  "Paul has hatched ! Please don’t forget to feed him. He eats three 🐛 every minute",
  "Your password must include the URL of a YouTube video of this exact length",
  "A sacrifice must be made. Pick two letters that you will no longer be able to use",
  "Your password must contain twice as many italic characters as bold",
  "At least 30% of your password must be in the Wingdings font",
  "Your password must include this color in hex",
  "All Roman numerals must be in Times New Roman",
  "The font size of every digit must be equal to its square",
  "Every instance of the same letter must have a different font size",
  "Your password must include the length of your password",
  "The length of your password must be a prime number",
  "This rule is skipped!",
  "Your password must include the current time",
];
